CREATE TABLE refresh_tokens (
  id UNIQUEIDENTIFIER PRIMARY KEY,
  user_id UNIQUEIDENTIFIER NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  expires_at DATETIME2 NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);