ALTER TABLE users
ADD role VARCHAR(50) DEFAULT 'USER';

ALTER TABLE users
ADD password VARCHAR(255) NOT NULL;

ALTER TABLE users
ALTER COLUMN name VARCHAR(255) NOT NULL;

ALTER TABLE users
ALTER COLUMN email VARCHAR(255) NOT NULL;
